version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
    container_name: code-pod-backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://localhost:8000/api
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env 
    container_name: code-pod-frontend